[bad_addresses]
filename = bad_addresses.csv
case_sensitive_match = false

[contract_baselines]
external_type = kvstore
collection = contract_baselines
fields_list = _key, contract_name, chain, mean_value_eth, stdev_value_eth, p99_value_eth, mean_gas, stdev_gas, tx_count_30d, failed_pct, dc_senders_30d, last_updated_epoch

[protocol_config]
filename = protocol_config.csv
